name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libmpv-dev
          sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ plucky main restricted" >> /etc/apt/sources.list'
          sudo apt-get -y update
          sudo apt-get -y install libssl-dev libgtk-4-dev libadwaita-1-dev libwebkitgtk-6.0-dev gettext nodejs

      - name: Lint fmt
        run: cargo fmt --all -- --check
      - name: Lint clippy
        run: cargo clippy --all --no-deps -- -D warnings
      - name: Build
        run: cargo build
